---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/git-resource

inputs:
  - name: lyra.git
  - name: lyra.version

outputs:
  - name: build
  
run:
  path: sh
  args:
    - -exc
    - |
      git clone lyra.git/ build/
