---
platform: linux

image_resource:
  type: docker-image
  source: { repository: hub.***REMOVED***/monsoon/kubectl, tag: 'v1.7.7'}

inputs:
- name: lyra.image 
- name: lyra.version

run:
  path: sh
  args:
    - -ec
    - |
      repository=$(cat lyra.image/repository)
      tag=$(cat lyra.version/current)
      echo kubectl set image deployment/$DEPLOYMENT --namespace=lyra $DEPLOYMENT=$repository:$tag
      kubectl set image deployment/$DEPLOYMENT --namespace=lyra $DEPLOYMENT=$repository:$tag
      echo Waiting for deployment to succeed 
      sleep $STEP #give the deployment a little time
      until kubectl get deployment $DEPLOYMENT --namespace=lyra -o json | \
              jq -e '.status | .unavailableReplicas == null and .replicas == .updatedReplicas' >/dev/null; do
        if [ $TIMEOUT -le 0 ]; then echo -e "\nTimeout waiting for deployment"; exit 1; fi 
        TIMEOUT=$((TIMEOUT-STEP))
        sleep $STEP 
        printf .
      done
      echo -e "\nDeployment completed"

params:
  STEP: 2
  TIMEOUT: 120
  REGION:
  GITHUB_TOKEN:
  DEPLOYMENT:
