---
platform: linux

image_resource:
  type: docker-image
  source: { repository: hub.***REMOVED***/monsoon/kubectl, tag: 'v1.7.7'}

inputs:
- name: lyra.version
- name: charts.git
- name: secrets.git

run:
  path: sh
  args:
    - -exc
    - |
      set -o pipefail
      lyra_version=$(cat lyra.version/current)
      helm upgrade $RELEASE charts.git/openstack/lyra  --values secrets.git/$REGION/values/lyra.yaml --set image.tag=$lyra_version
      kubectl rollout status deployment/$RELEASE-api --namespace=$NAMESPACE
      kubectl rollout status deployment/$RELEASE-worker --namespace=$NAMESPACE

params:
  STEP: 2
  TIMEOUT: 300
  REGION:
  GITHUB_TOKEN:
  HELM_HOST:
  NAMESPACE: lyra
  RELEASE: lyra
