---
platform: linux

image_resource:
  type: docker-image
  source: { repository: hub.***REMOVED***/monsoon/kubectl, tag: 'v1.4.6'}

inputs:
- name: lyra.version
- name: charts.git
- name: secrets.git

run:
  path: sh
  args:
    - -exc
    - |
      set -o pipefail
      lyra_version=$(cat lyra.version/current)
      helm upgrade $RELEASE charts.git/openstack/lyra  --values secrets.git/$REGION/values/lyra.yaml --set image.tag=$lyra_version --debug
      kubectl rollout status deployment/$RELEASE-api --namespace=$NAMESPACE
      kubectl rollout status deployment/$RELEASE-worker --namespace=$NAMESPACE
      set +x
      for deployment in api worker; do
        echo "Waiting for $deployment deployment to succeed"
        until kubectl get deployment $RELEASE-$deployment  --namespace=$NAMESPACE -o json | \
                jq -e '.status | .unavailableReplicas == null and .replicas == .updatedReplicas' >/dev/null; do
          if [ $TIMEOUT -le 0 ]; then echo -e "\nTimeout waiting for $deployment deployment"; exit 1; fi 
          TIMEOUT=$((TIMEOUT-STEP))
          sleep $STEP
          printf .
        done
        echo -e "\n$deployment deployment completed"
      done

params:
  STEP: 2
  TIMEOUT: 120
  REGION:
  GITHUB_TOKEN:
  HELM_HOST:
  NAMESPACE: lyra
  RELEASE: lyra
