---
platform: linux

# 1. install postgres and bash
# 2. run postgres via pg_tmp
# 3. create and migrate database
# 4. run tests
# 5. stop postgres

inputs:
  - name: lyra.git

run:
  path: sh
  args:
    - -exc
    - |
      apk add --no-cache postgresql bash
      export LISTENTO=127.0.0.1
      su postgres -c 'lyra.git/ci/scripts/pg_tmp.sh -p 5432 -w 300 -d /tmp/pg start'
      cd /home/app/webapp
      bundle exec rake db:create db:migrate RAILS_ENV=test
      bundle exec rspec
      cd -
      su postgres -c 'lyra.git/ci/scripts/pg_tmp.sh -d /tmp/pg stop'
