---
platform: linux

# 1. install postgres and bash
# 2. run postgres via pg_tmp
# 3. create and migrate database
# 4. run tests
# 5. stop postgres

run:
  path: sh
  args:
    - -exc
    - |
      apk add --no-cache postgresql bash
      cd /home/app/webapp
      su postgres -c 'ci/scripts/pg_tmp.sh -p 5432 -l 127.0.0.1 -w 300 -d /tmp/pg start'
      rake db:create db:migrate
      bundle exec rspec
      su postgres -c 'ci/scripts/pg_tmp.sh -d /tmp/pg stop'

